export interface DrugItem {
  id: string;
  name: string;
  genericName: string;
  brandNames: string[];
  category: string;
  form:
    | 'Tablet'
    | 'Capsule'
    | 'Syrup'
    | 'Injection'
    | 'Ointment'
    | 'Drops'
    | 'Inhaler'
    | 'Sachet'
    | 'IV Fluid'
    | 'Gel'
    | 'Cream'
    | 'Lotion'
    | 'Medical Consumable'
    | 'Surgical & Device'
    | 'Catheter'
    | 'Tube';
  defaultStrength: string;
  defaultDosage: string;
  defaultTiming: string;
  defaultDuration: string;
  defaultInstruction: string;
}

export const DRUG_CATEGORIES = [
  "All",
  "Pain & Fever",
  "Antibiotics",
  "Gastro & Antacids",
  "Cough, Cold & Allergy",
  "Cardio & BP",
  "Diabetes",
  "Vitamins & Supplements",
  "Dermatology",
  "Eye & ENT",
  "IV Fluids & Electrolytes",
  "Injectables & Emergency",
  "Ointments, Gels & Topicals",
  "Surgical & Medical Consumables",
] as const;

export const MEDICATION_PREFIXES = [
  "Tab.",
  "Cap.",
  "Syr.",
  "Inj.",
  "IVF.",
  "Oint.",
  "Cream",
  "Gel",
  "Lotion",
  "Drops",
  "Inh.",
  "Sachet",
  "Susp.",
  "Tube",
  "Cath.",
  "Set",
  "Cons.",
  "Surg.",
  "Powder",
  "Spray",
] as const;

export const FORM_PREFIX_MAP: Record<DrugItem['form'], string> = {
  Tablet: "Tab.",
  Capsule: "Cap.",
  Syrup: "Syr.",
  Injection: "Inj.",
  Ointment: "Oint.",
  Drops: "Drops",
  Inhaler: "Inh.",
  Sachet: "Sachet",
  "IV Fluid": "IVF.",
  Gel: "Gel",
  Cream: "Cream",
  Lotion: "Lotion",
  "Medical Consumable": "Cons.",
  "Surgical & Device": "Surg.",
  Catheter: "Cath.",
  Tube: "Tube",
};

export const DRUG_LIBRARY: DrugItem[] = [
  // --- PAIN & FEVER / NSAIDs ---
  {
    id: "pcm-650",
    name: "Paracetamol 650mg",
    genericName: "PARACETAMOL",
    brandNames: ["Dolo 650", "Calpol 650", "Pacimol 650"],
    category: "Pain & Fever",
    form: "Tablet",
    defaultStrength: "650mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "3 days",
    defaultInstruction: "Take with water after food; SOS for fever > 100°F or severe body ache",
  },
  {
    id: "pcm-500",
    name: "Paracetamol 500mg",
    genericName: "PARACETAMOL",
    brandNames: ["Crocin 500", "Calpol 500"],
    category: "Pain & Fever",
    form: "Tablet",
    defaultStrength: "500mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "3 days",
    defaultInstruction: "Take after food as needed for mild fever or headache",
  },
  {
    id: "aceclo-pcm",
    name: "Aceclofenac + Paracetamol",
    genericName: "ACECLOFENAC (100MG) + PARACETAMOL (325MG)",
    brandNames: ["Zerodol-P", "Hifenac-P", "Aroff Plus"],
    category: "Pain & Fever",
    form: "Tablet",
    defaultStrength: "100mg/325mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "5 days",
    defaultInstruction: "Take after food with plenty of water. Avoid on empty stomach.",
  },
  {
    id: "ibup-400",
    name: "Ibuprofen 400mg",
    genericName: "IBUPROFEN",
    brandNames: ["Brufen 400", "Ibugesic 400"],
    category: "Pain & Fever",
    form: "Tablet",
    defaultStrength: "400mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "3 days",
    defaultInstruction: "Anti-inflammatory pain relief; always take after meals",
  },
  {
    id: "diclo-50",
    name: "Diclofenac Sodium 50mg",
    genericName: "DICLOFENAC SODIUM",
    brandNames: ["Voveran 50", "Dicloran 50"],
    category: "Pain & Fever",
    form: "Tablet",
    defaultStrength: "50mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "3 days",
    defaultInstruction: "Take after food with an antacid if acidity-prone",
  },
  {
    id: "tram-pcm",
    name: "Tramadol + Paracetamol",
    genericName: "TRAMADOL (37.5MG) + PARACETAMOL (325MG)",
    brandNames: ["Ultracet", "Calpol-T"],
    category: "Pain & Fever",
    form: "Tablet",
    defaultStrength: "37.5mg/325mg",
    defaultDosage: "SOS",
    defaultTiming: "After food",
    defaultDuration: "3 days",
    defaultInstruction: "Take only SOS for severe acute pain; may cause mild drowsiness",
  },
  {
    id: "meftal-spas",
    name: "Mefenamic Acid + Dicyclomine",
    genericName: "MEFENAMIC ACID (250MG) + DICYCLOMINE (10MG)",
    brandNames: ["Meftal-Spas", "Spasmo-Proxyvon"],
    category: "Pain & Fever",
    form: "Tablet",
    defaultStrength: "250mg/10mg",
    defaultDosage: "SOS",
    defaultTiming: "After food",
    defaultDuration: "3 days",
    defaultInstruction: "For abdominal spasmodic cramps or dysmenorrhea",
  },

  // --- ANTIBIOTICS & ANTIMICROBIALS ---
  {
    id: "amox-clav-625",
    name: "Amoxicillin + Clavulanic Acid 625mg",
    genericName: "AMOXICILLIN (500MG) + CLAVULANIC ACID (125MG)",
    brandNames: ["Augmentin 625 Duo", "Clavam 625", "Moxikind-CV 625"],
    category: "Antibiotics",
    form: "Tablet",
    defaultStrength: "625mg",
    defaultDosage: "1-0-1",
    defaultTiming: "With food",
    defaultDuration: "5 days",
    defaultInstruction: "Complete the full 5-day course. Take at start of meals to minimize stomach upset.",
  },
  {
    id: "azithro-500",
    name: "Azithromycin 500mg",
    genericName: "AZITHROMYCIN",
    brandNames: ["Azee 500", "Zithrox 500", "Azithral 500"],
    category: "Antibiotics",
    form: "Tablet",
    defaultStrength: "500mg",
    defaultDosage: "1-0-0",
    defaultTiming: "Before food",
    defaultDuration: "3 days",
    defaultInstruction: "Single daily dose 1 hour before breakfast or 2 hours after meals",
  },
  {
    id: "cefix-200",
    name: "Cefixime 200mg",
    genericName: "CEFIXIME",
    brandNames: ["Zifi 200", "Taxim-O 200", "Cephalkem 200"],
    category: "Antibiotics",
    form: "Tablet",
    defaultStrength: "200mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "5 days",
    defaultInstruction: "Complete prescribed course for bacterial infection",
  },
  {
    id: "cipro-500",
    name: "Ciprofloxacin 500mg",
    genericName: "CIPROFLOXACIN",
    brandNames: ["Ciplox 500", "Cifran 500"],
    category: "Antibiotics",
    form: "Tablet",
    defaultStrength: "500mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "5 days",
    defaultInstruction: "Drink plenty of water during treatment. Avoid taking with antacids or dairy.",
  },
  {
    id: "oflox-ornid",
    name: "Ofloxacin + Ornidazole",
    genericName: "OFLOXACIN (200MG) + ORNIDAZOLE (500MG)",
    brandNames: ["O2", "Zenflox-OZ", "Oflomac-OZ"],
    category: "Antibiotics",
    form: "Tablet",
    defaultStrength: "200mg/500mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "5 days",
    defaultInstruction: "For mixed gastrointestinal or urinary infections; avoid alcohol completely",
  },
  {
    id: "doxy-100",
    name: "Doxycycline 100mg",
    genericName: "DOXYCYCLINE",
    brandNames: ["Doxicip 100", "Microdox-LBX"],
    category: "Antibiotics",
    form: "Capsule",
    defaultStrength: "100mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "7 days",
    defaultInstruction: "Take with a full glass of water sitting upright. Do not lie down for 30 minutes.",
  },
  {
    id: "nitro-100",
    name: "Nitrofurantoin 100mg SR",
    genericName: "NITROFURANTOIN SUSTAINED RELEASE",
    brandNames: ["Niftran 100", "Martifur MR 100"],
    category: "Antibiotics",
    form: "Tablet",
    defaultStrength: "100mg",
    defaultDosage: "1-0-1",
    defaultTiming: "With food",
    defaultDuration: "7 days",
    defaultInstruction: "For urinary tract infection; take with food or milk to enhance absorption",
  },
  {
    id: "metronid-400",
    name: "Metronidazole 400mg",
    genericName: "METRONIDAZOLE",
    brandNames: ["Flagyl 400", "Metrogyl 400"],
    category: "Antibiotics",
    form: "Tablet",
    defaultStrength: "400mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "5 days",
    defaultInstruction: "For amoebic / anaerobic infections; strictly avoid alcohol",
  },

  // --- GASTROINTESTINAL & ANTACIDS ---
  {
    id: "panto-40",
    name: "Pantoprazole 40mg",
    genericName: "PANTOPRAZOLE",
    brandNames: ["Pan 40", "Pantocid 40", "Pantodac 40"],
    category: "Gastro & Antacids",
    form: "Tablet",
    defaultStrength: "40mg",
    defaultDosage: "1-0-0",
    defaultTiming: "Empty stomach",
    defaultDuration: "14 days",
    defaultInstruction: "Take 30 minutes before breakfast on empty stomach with water",
  },
  {
    id: "panto-dom-dsr",
    name: "Pantoprazole + Domperidone SR",
    genericName: "PANTOPRAZOLE (40MG) + DOMPERIDONE (30MG SR)",
    brandNames: ["Pan-D", "Pantocid-DSR", "Dompan-SR"],
    category: "Gastro & Antacids",
    form: "Capsule",
    defaultStrength: "40mg/30mg",
    defaultDosage: "1-0-0",
    defaultTiming: "Empty stomach",
    defaultDuration: "14 days",
    defaultInstruction: "Take 30-45 minutes before morning breakfast for GERD & reflux",
  },
  {
    id: "rabe-dom-dsr",
    name: "Rabeprazole + Domperidone",
    genericName: "RABEPRAZOLE (20MG) + DOMPERIDONE (30MG SR)",
    brandNames: ["Razo-D", "Cyra-D", "Rablet-D"],
    category: "Gastro & Antacids",
    form: "Capsule",
    defaultStrength: "20mg/30mg",
    defaultDosage: "1-0-0",
    defaultTiming: "Empty stomach",
    defaultDuration: "14 days",
    defaultInstruction: "Take before breakfast on empty stomach",
  },
  {
    id: "omez-20",
    name: "Omeprazole 20mg",
    genericName: "OMEPRAZOLE",
    brandNames: ["Omez 20", "Ocid 20"],
    category: "Gastro & Antacids",
    form: "Capsule",
    defaultStrength: "20mg",
    defaultDosage: "1-0-0",
    defaultTiming: "Empty stomach",
    defaultDuration: "14 days",
    defaultInstruction: "Take before breakfast for acid peptic relief",
  },
  {
    id: "ondan-4",
    name: "Ondansetron 4mg MD",
    genericName: "ONDANSETRON MOUTH DISSOLVING",
    brandNames: ["Emeset 4 MD", "Zofer 4 MD", "Vomikind MD"],
    category: "Gastro & Antacids",
    form: "Tablet",
    defaultStrength: "4mg",
    defaultDosage: "SOS",
    defaultTiming: "Before food",
    defaultDuration: "3 days",
    defaultInstruction: "Dissolve on tongue 30 mins before food or SOS for nausea/vomiting",
  },
  {
    id: "sucralfate-syr",
    name: "Sucralfate + Oxetacaine Suspension",
    genericName: "SUCRALFATE (1000MG) + OXETACAINE (20MG)",
    brandNames: ["Sucrafil-O", "Pegafate-O"],
    category: "Gastro & Antacids",
    form: "Syrup",
    defaultStrength: "10ml",
    defaultDosage: "1-0-1",
    defaultTiming: "Before food",
    defaultDuration: "14 days",
    defaultInstruction: "Take 10ml 1 hour before meals and at bedtime for mucosal healing",
  },
  {
    id: "ors-powder",
    name: "Oral Rehydration Salts (ORS)",
    genericName: "WHO FORMULA ORAL ELECTROLYTES",
    brandNames: ["Electral Powder", "Walyte ORS"],
    category: "Gastro & Antacids",
    form: "Sachet",
    defaultStrength: "21.8g Sachet",
    defaultDosage: "SOS",
    defaultTiming: "With food",
    defaultDuration: "3 days",
    defaultInstruction: "Dissolve 1 sachet entirely in 1 Litre of clean drinking water; sip frequently",
  },

  // --- COUGH, COLD & RESPIRATORY ---
  {
    id: "levocet-5",
    name: "Levocetirizine 5mg",
    genericName: "LEVOCETIRIZINE DIHYDROCHLORIDE",
    brandNames: ["Levocet 5", "1-AL 5", "Vozet 5"],
    category: "Cough, Cold & Allergy",
    form: "Tablet",
    defaultStrength: "5mg",
    defaultDosage: "0-0-1",
    defaultTiming: "At bedtime",
    defaultDuration: "5 days",
    defaultInstruction: "Take once daily at bedtime for allergic rhinitis, sneezing, and itching",
  },
  {
    id: "montair-lc",
    name: "Montelukast + Levocetirizine",
    genericName: "MONTELUKAST (10MG) + LEVOCETIRIZINE (5MG)",
    brandNames: ["Montair-LC", "Monticope", "Telekast-L"],
    category: "Cough, Cold & Allergy",
    form: "Tablet",
    defaultStrength: "10mg/5mg",
    defaultDosage: "0-0-1",
    defaultTiming: "At bedtime",
    defaultDuration: "10 days",
    defaultInstruction: "Take at bedtime for allergic asthma, chronic cough, and allergic rhinitis",
  },
  {
    id: "fexo-120",
    name: "Fexofenadine 120mg",
    genericName: "FEXOFENADINE HYDROCHLORIDE",
    brandNames: ["Allegra 120", "Fexova 120"],
    category: "Cough, Cold & Allergy",
    form: "Tablet",
    defaultStrength: "120mg",
    defaultDosage: "1-0-0",
    defaultTiming: "After food",
    defaultDuration: "7 days",
    defaultInstruction: "Non-sedating antihistamine for urticaria and seasonal allergies",
  },
  {
    id: "cough-dry",
    name: "Dextromethorphan + CPM Syrup",
    genericName: "DEXTROMETHORPHAN HBR + CHLORPHENIRAMINE MALEATE",
    brandNames: ["Ascoril-D", "Benadryl DR", "Alex Syrup"],
    category: "Cough, Cold & Allergy",
    form: "Syrup",
    defaultStrength: "10ml",
    defaultDosage: "1-1-1",
    defaultTiming: "After food",
    defaultDuration: "5 days",
    defaultInstruction: "10ml thrice daily for dry irritant cough; avoid driving if drowsy",
  },
  {
    id: "cough-wet",
    name: "Ambroxol + Levosalbutamol + Guaiphenesin",
    genericName: "MUCOLYTIC & BRONCHODILATOR EXPECTORANT",
    brandNames: ["Ascoril-LS", "Bro-Zedex LS", "Grilinctus-LS"],
    category: "Cough, Cold & Allergy",
    form: "Syrup",
    defaultStrength: "10ml",
    defaultDosage: "1-1-1",
    defaultTiming: "After food",
    defaultDuration: "5 days",
    defaultInstruction: "10ml thrice daily with lukewarm water to loosen chest congestion",
  },
  {
    id: "sinarest",
    name: "Paracetamol + Phenylephrine + Chlorpheniramine",
    genericName: "ANTIPYRETIC + DECONGESTANT + ANTIHISTAMINIC",
    brandNames: ["Sinarest", "Cheston Cold", "Wikoryl"],
    category: "Cough, Cold & Allergy",
    form: "Tablet",
    defaultStrength: "Combination",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "3 days",
    defaultInstruction: "Relief of common cold, blocked nose, fever, and headache",
  },
  {
    id: "asthalin-inhaler",
    name: "Salbutamol Inhaler 100mcg",
    genericName: "SALBUTAMOL SULFATE",
    brandNames: ["Asthalin Inhaler", "Ventorlin"],
    category: "Cough, Cold & Allergy",
    form: "Inhaler",
    defaultStrength: "100mcg/puff",
    defaultDosage: "SOS",
    defaultTiming: "As needed (SOS)",
    defaultDuration: "1 month",
    defaultInstruction: "1 to 2 puffs SOS for acute breathlessness or wheezing; rinse mouth after use",
  },
  {
    id: "foracort-200",
    name: "Budesonide + Formoterol Inhaler 200",
    genericName: "BUDESONIDE (200MCG) + FORMOTEROL (6MCG)",
    brandNames: ["Foracort 200 Rotacaps/Inhaler", "Budamate 200"],
    category: "Cough, Cold & Allergy",
    form: "Inhaler",
    defaultStrength: "200mcg/6mcg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "1 inhalation twice daily regularly. Gargle and rinse mouth thoroughly with water after use.",
  },

  // --- CARDIOVASCULAR & ANTIHYPERTENSIVES ---
  {
    id: "telma-40",
    name: "Telmisartan 40mg",
    genericName: "TELMISARTAN",
    brandNames: ["Telma 40", "Telmikind 40", "Creser 40"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "40mg",
    defaultDosage: "1-0-0",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "Take in the morning regularly; monitor blood pressure regularly",
  },
  {
    id: "telma-am",
    name: "Telmisartan 40mg + Amlodipine 5mg",
    genericName: "TELMISARTAN (40MG) + AMLODIPINE (5MG)",
    brandNames: ["Telma-AM", "Telmikind-AM", "Amlokind-T"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "40mg/5mg",
    defaultDosage: "1-0-0",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "Take once daily in morning for essential hypertension",
  },
  {
    id: "amlong-5",
    name: "Amlodipine 5mg",
    genericName: "AMLODIPINE BESYLATE",
    brandNames: ["Amlong 5", "Stamlo 5", "Amlopin 5"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "5mg",
    defaultDosage: "0-0-1",
    defaultTiming: "At bedtime",
    defaultDuration: "1 month",
    defaultInstruction: "Take once daily at evening/bedtime; report pedal swelling if observed",
  },
  {
    id: "atorva-10",
    name: "Atorvastatin 10mg",
    genericName: "ATORVASTATIN CALCIUM",
    brandNames: ["Atorva 10", "Storvas 10", "Lipicure 10"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "10mg",
    defaultDosage: "0-0-1",
    defaultTiming: "At bedtime",
    defaultDuration: "1 month",
    defaultInstruction: "Lipid-lowering statin; take once daily at bedtime",
  },
  {
    id: "atorva-20",
    name: "Atorvastatin 20mg",
    genericName: "ATORVASTATIN CALCIUM",
    brandNames: ["Atorva 20", "Storvas 20", "Lipicure 20"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "20mg",
    defaultDosage: "0-0-1",
    defaultTiming: "At bedtime",
    defaultDuration: "1 month",
    defaultInstruction: "Take once daily at bedtime for dyslipidemia / cardiovascular risk reduction",
  },
  {
    id: "rosuvas-10",
    name: "Rosuvastatin 10mg",
    genericName: "ROSUVASTATIN CALCIUM",
    brandNames: ["Rosuvas 10", "Rozavel 10", "Roseday 10"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "10mg",
    defaultDosage: "0-0-1",
    defaultTiming: "At bedtime",
    defaultDuration: "1 month",
    defaultInstruction: "High-efficacy statin for cholesterol control; take at night",
  },
  {
    id: "metolar-25",
    name: "Metoprolol Succinate 25mg ER",
    genericName: "METOPROLOL SUCCINATE EXTENDED RELEASE",
    brandNames: ["Betaloc 25", "Metolar XR 25", "Pro lomet 25"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "25mg",
    defaultDosage: "1-0-0",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "Beta-blocker; take once daily with breakfast",
  },
  {
    id: "ecosprin-75",
    name: "Aspirin (Ecosprin) 75mg",
    genericName: "ASPIRIN (ENTERIC COATED)",
    brandNames: ["Ecosprin 75", "Delisprin 75"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "75mg",
    defaultDosage: "0-1-0",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "Antiplatelet cardioprotective dose; always take after afternoon or morning meal",
  },
  {
    id: "clopi-75",
    name: "Clopidogrel 75mg",
    genericName: "CLOPIDOGREL BISULFATE",
    brandNames: ["Clopilet 75", "Deplatt 75"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "75mg",
    defaultDosage: "0-1-0",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "Antiplatelet therapy; take daily after lunch",
  },

  // --- ANTIDIABETICS & ENDOCRINE ---
  {
    id: "metform-500",
    name: "Metformin 500mg SR",
    genericName: "METFORMIN HYDROCHLORIDE SUSTAINED RELEASE",
    brandNames: ["Glycomet 500 SR", "Cetapin 500", "Obimet 500"],
    category: "Diabetes",
    form: "Tablet",
    defaultStrength: "500mg",
    defaultDosage: "1-0-1",
    defaultTiming: "With food",
    defaultDuration: "1 month",
    defaultInstruction: "Take immediately with or after meals to prevent gastric irritation",
  },
  {
    id: "metform-1000",
    name: "Metformin 1000mg SR",
    genericName: "METFORMIN HYDROCHLORIDE SUSTAINED RELEASE",
    brandNames: ["Glycomet 1000 SR", "Gluconorm-SR 1g"],
    category: "Diabetes",
    form: "Tablet",
    defaultStrength: "1000mg",
    defaultDosage: "1-0-1",
    defaultTiming: "With food",
    defaultDuration: "1 month",
    defaultInstruction: "Take with meals; monitor HbA1c and renal parameters periodically",
  },
  {
    id: "glycomet-gp1",
    name: "Metformin 500mg + Glimepiride 1mg",
    genericName: "GLIMEPIRIDE (1MG) + METFORMIN (500MG SR)",
    brandNames: ["Glycomet-GP 1", "Amaryl M 1", "Zoryl-M 1"],
    category: "Diabetes",
    form: "Tablet",
    defaultStrength: "500mg/1mg",
    defaultDosage: "1-0-0",
    defaultTiming: "Before food",
    defaultDuration: "1 month",
    defaultInstruction: "Take 15-20 minutes before breakfast; maintain regular meal timings to avoid hypoglycemia",
  },
  {
    id: "glycomet-gp2",
    name: "Metformin 500mg + Glimepiride 2mg",
    genericName: "GLIMEPIRIDE (2MG) + METFORMIN (500MG SR)",
    brandNames: ["Glycomet-GP 2", "Amaryl M 2", "Zoryl-M 2"],
    category: "Diabetes",
    form: "Tablet",
    defaultStrength: "500mg/2mg",
    defaultDosage: "1-0-0",
    defaultTiming: "Before food",
    defaultDuration: "1 month",
    defaultInstruction: "Take before breakfast; keep glucose/sugar handy for hypoglycemia prevention",
  },
  {
    id: "teneli-20",
    name: "Teneligliptin 20mg",
    genericName: "TENELIGLIPTIN HYDROBROMIDE",
    brandNames: ["Ziten 20", "Tendia 20", "Tenelimac 20"],
    category: "Diabetes",
    form: "Tablet",
    defaultStrength: "20mg",
    defaultDosage: "1-0-0",
    defaultTiming: "Before food",
    defaultDuration: "1 month",
    defaultInstruction: "DPP-4 inhibitor; take once daily before breakfast",
  },
  {
    id: "dapa-10",
    name: "Dapagliflozin 10mg",
    genericName: "DAPAGLIFLOZIN PROPANEDIOL",
    brandNames: ["Forxiga 10", "Oxra 10", "Dapavel 10"],
    category: "Diabetes",
    form: "Tablet",
    defaultStrength: "10mg",
    defaultDosage: "1-0-0",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "SGLT-2 inhibitor; drink adequate water throughout the day",
  },
  {
    id: "thyro-50",
    name: "Levothyroxine 50mcg",
    genericName: "LEVOTHYROXINE SODIUM",
    brandNames: ["Thyronorm 50mcg", "Eltroxin 50mcg"],
    category: "Diabetes",
    form: "Tablet",
    defaultStrength: "50mcg",
    defaultDosage: "1-0-0",
    defaultTiming: "Empty stomach",
    defaultDuration: "1 month",
    defaultInstruction: "Take early morning on empty stomach with plain water at least 45 mins before tea/coffee",
  },
  {
    id: "thyro-100",
    name: "Levothyroxine 100mcg",
    genericName: "LEVOTHYROXINE SODIUM",
    brandNames: ["Thyronorm 100mcg", "Eltroxin 100mcg"],
    category: "Diabetes",
    form: "Tablet",
    defaultStrength: "100mcg",
    defaultDosage: "1-0-0",
    defaultTiming: "Empty stomach",
    defaultDuration: "1 month",
    defaultInstruction: "Take early morning on empty stomach with plain water. Repeat TSH in 8-12 weeks.",
  },

  // --- VITAMINS, MINERALS & SUPPLEMENTS ---
  {
    id: "shelcal-500",
    name: "Calcium 500mg + Vitamin D3",
    genericName: "CALCIUM CARBONATE (500MG ELEMENTAL) + VITAMIN D3 (250 IU)",
    brandNames: ["Shelcal 500", "Cipcal 500", "Gemcal"],
    category: "Vitamins & Supplements",
    form: "Tablet",
    defaultStrength: "500mg",
    defaultDosage: "0-1-0",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "Take once daily after lunch with water",
  },
  {
    id: "vit-d3-60k",
    name: "Cholecalciferol (Vitamin D3) 60,000 IU",
    genericName: "CHOLECALCIFEROL VITAMIN D3",
    brandNames: ["Uprise-D3 60K", "Calcirol 60K Sachet", "D-Rise 60K"],
    category: "Vitamins & Supplements",
    form: "Capsule",
    defaultStrength: "60,000 IU",
    defaultDosage: "Weekly once",
    defaultTiming: "After food",
    defaultDuration: "2 months",
    defaultInstruction: "Take 1 capsule once weekly (e.g. every Sunday after breakfast with milk) for 8 weeks",
  },
  {
    id: "neurobion",
    name: "Vitamin B-Complex + B12",
    genericName: "THIAMINE, RIBOFLAVIN, NIACINAMIDE, PYRIDOXINE, CYANOCOBALAMIN",
    brandNames: ["Neurobion Forte", "Becosules", "Cobadex Forte"],
    category: "Vitamins & Supplements",
    form: "Tablet",
    defaultStrength: "High Potency B-Complex",
    defaultDosage: "1-0-0",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "Daily multivitamin after breakfast to maintain nerve health & energy",
  },
  {
    id: "iron-folic",
    name: "Ferrous Ascorbate + Folic Acid",
    genericName: "FERROUS ASCORBATE (100MG ELEMENTAL IRON) + FOLIC ACID (1.5MG)",
    brandNames: ["Orofer-XT", "HB-Rich", "Feronia-XT"],
    category: "Vitamins & Supplements",
    form: "Tablet",
    defaultStrength: "100mg/1.5mg",
    defaultDosage: "0-0-1",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "For iron deficiency anemia; take at bedtime. Avoid taking with tea, coffee, or milk.",
  },
  {
    id: "vit-c-zinc",
    name: "Vitamin C 500mg + Zinc",
    genericName: "ASCORBIC ACID (500MG) + ZINC (5MG)",
    brandNames: ["Limcee Chewable", "Celin 500", "Zinconia"],
    category: "Vitamins & Supplements",
    form: "Tablet",
    defaultStrength: "500mg",
    defaultDosage: "1-0-0",
    defaultTiming: "After food",
    defaultDuration: "15 days",
    defaultInstruction: "Chewable tablet; immune support for recovery from infections",
  },

  // --- DERMATOLOGY & TOPICALS ---
  {
    id: "tbact-oint",
    name: "Mupirocin 2% Ointment",
    genericName: "MUPIROCIN OINTMENT 2% W/W",
    brandNames: ["T-Bact Ointment", "Bactroban"],
    category: "Dermatology",
    form: "Ointment",
    defaultStrength: "2%",
    defaultDosage: "1-0-1",
    defaultTiming: "As needed (SOS)",
    defaultDuration: "7 days",
    defaultInstruction: "Apply thinly over cleaned affected area twice daily for bacterial skin infection",
  },
  {
    id: "candid-cream",
    name: "Clotrimazole 1% Cream",
    genericName: "CLOTRIMAZOLE CREAM 1% W/W",
    brandNames: ["Candid Cream", "Canesten"],
    category: "Dermatology",
    form: "Ointment",
    defaultStrength: "1%",
    defaultDosage: "1-0-1",
    defaultTiming: "As needed (SOS)",
    defaultDuration: "14 days",
    defaultInstruction: "Clean and dry skin thoroughly; apply twice daily for fungal ringworm / tinea infection",
  },
  {
    id: "betnovate-n",
    name: "Betamethasone + Neomycin Cream",
    genericName: "BETAMETHASONE VALERATE (0.1%) + NEOMYCIN (0.5%)",
    brandNames: ["Betnovate-N", "Cortiderm-N"],
    category: "Dermatology",
    form: "Ointment",
    defaultStrength: "0.1%/0.5%",
    defaultDosage: "1-0-1",
    defaultTiming: "As needed (SOS)",
    defaultDuration: "5 days",
    defaultInstruction: "Apply sparingly on affected eczema / dermatitis lesion for short-term relief",
  },

  // --- EYE & ENT DROPS ---
  {
    id: "moxi-eye",
    name: "Moxifloxacin 0.5% Eye Drops",
    genericName: "MOXIFLOXACIN OPHTHALMIC SOLUTION 0.5% W/V",
    brandNames: ["Moxicip Eye Drops", "Vigamox"],
    category: "Eye & ENT",
    form: "Drops",
    defaultStrength: "0.5%",
    defaultDosage: "1-1-1",
    defaultTiming: "As needed (SOS)",
    defaultDuration: "5 days",
    defaultInstruction: "Instill 1 drop in affected eye(s) 3 times daily for conjunctivitis",
  },
  {
    id: "refresh-tears",
    name: "Carboxymethylcellulose 0.5% Eye Drops",
    genericName: "CARBOXYMETHYLCELLULOSE LUBRICANT EYE DROPS",
    brandNames: ["Refresh Tears", "Tears Naturale", "Lubrex"],
    category: "Eye & ENT",
    form: "Drops",
    defaultStrength: "0.5%",
    defaultDosage: "1-1-1-1",
    defaultTiming: "As needed (SOS)",
    defaultDuration: "1 month",
    defaultInstruction: "Instill 1-2 drops 3 to 4 times daily for dry, tired, or strained eyes",
  },
  {
    id: "ciplox-ear",
    name: "Ciprofloxacin Ear Drops",
    genericName: "CIPROFLOXACIN 0.3% W/V EAR DROPS",
    brandNames: ["Ciplox Ear Drops", "Cifran Ear Drops"],
    category: "Eye & ENT",
    form: "Drops",
    defaultStrength: "0.3%",
    defaultDosage: "1-0-1",
    defaultTiming: "As needed (SOS)",
    defaultDuration: "5 days",
    defaultInstruction: "Instill 3-4 drops into affected ear canal twice daily; keep ear dry",
  },
  {
    id: "otrivin-drops",
    name: "Xylometazoline 0.1% Nasal Drops",
    genericName: "XYLOMETAZOLINE HYDROCHLORIDE 0.1%",
    brandNames: ["Otrivin Nasal Drops", "Nasivion"],
    category: "Eye & ENT",
    form: "Drops",
    defaultStrength: "0.1%",
    defaultDosage: "1-0-1",
    defaultTiming: "As needed (SOS)",
    defaultDuration: "3 days",
    defaultInstruction: "Instill 2 drops in each nostril for blocked nose; do NOT use for more than 5 consecutive days",
  },

  // =========================================================================
  // IV FLUIDS & ELECTROLYTES
  // =========================================================================
  {
    id: "ivf-rl-500",
    name: "Ringer's Lactate (RL) 500ml",
    genericName: "SODIUM LACTATE, SODIUM CHLORIDE, POTASSIUM CHLORIDE, CALCIUM CHLORIDE",
    brandNames: ["RL 500ml", "Ringer Lactate", "Hartmann's Solution", "RL Infusion"],
    category: "IV Fluids & Electrolytes",
    form: "IV Fluid",
    defaultStrength: "500ml",
    defaultDosage: "1 bottle IV",
    defaultTiming: "Slow IV infusion",
    defaultDuration: "Stat / As directed",
    defaultInstruction: "Infuse via IV set under clinical monitoring at 20-30 drops/min for resuscitation & dehydration",
  },
  {
    id: "ivf-dns-500",
    name: "Dextrose Normal Saline (DNS) 500ml",
    genericName: "5% DEXTROSE WITH 0.9% SODIUM CHLORIDE",
    brandNames: ["DNS 500ml", "Dextrose Saline", "DNS Infusion"],
    category: "IV Fluids & Electrolytes",
    form: "IV Fluid",
    defaultStrength: "500ml",
    defaultDosage: "1 bottle IV",
    defaultTiming: "Slow IV infusion",
    defaultDuration: "Stat / 1 day",
    defaultInstruction: "Check capillary blood glucose before infusing; monitor drip rate carefully",
  },
  {
    id: "ivf-ns-500",
    name: "Normal Saline (NS 0.9%) 500ml",
    genericName: "0.9% SODIUM CHLORIDE INJECTION",
    brandNames: ["NS 500ml", "Normal Saline 0.9%", "Saline Infusion"],
    category: "IV Fluids & Electrolytes",
    form: "IV Fluid",
    defaultStrength: "500ml",
    defaultDosage: "1 bottle IV",
    defaultTiming: "IV infusion",
    defaultDuration: "Stat / 1 day",
    defaultInstruction: "Isotonic crystalloid for fluid resuscitation, medication vehicle, and line maintenance",
  },
  {
    id: "ivf-ns-100",
    name: "Normal Saline (NS 0.9%) 100ml Mini Bag",
    genericName: "0.9% SODIUM CHLORIDE FOR DILUTION",
    brandNames: ["NS 100ml", "Saline 100ml Mini Bottle"],
    category: "IV Fluids & Electrolytes",
    form: "IV Fluid",
    defaultStrength: "100ml",
    defaultDosage: "1 mini bag",
    defaultTiming: "IV piggyback",
    defaultDuration: "Stat",
    defaultInstruction: "Vehicle for intravenous drug dilution (Ceftriaxone, Pantoprazole, Paracetamol)",
  },
  {
    id: "ivf-d5-500",
    name: "Dextrose 5% (D5W) 500ml",
    genericName: "5% DEXTROSE ANHYDROUS INFUSION",
    brandNames: ["D5 500ml", "Dextrose 5% Solution"],
    category: "IV Fluids & Electrolytes",
    form: "IV Fluid",
    defaultStrength: "500ml",
    defaultDosage: "1 bottle IV",
    defaultTiming: "Slow IV infusion",
    defaultDuration: "Stat",
    defaultInstruction: "For free water replacement and carbohydrate source; avoid in neuro-trauma / stroke",
  },
  {
    id: "ivf-d25-100",
    name: "Dextrose 25% (D25) 100ml",
    genericName: "25% HYPERTONIC DEXTROSE MONOHYDRATE",
    brandNames: ["D25 100ml", "Hypertonic Glucose 25%"],
    category: "IV Fluids & Electrolytes",
    form: "IV Fluid",
    defaultStrength: "100ml",
    defaultDosage: "50-100ml slow IV stat",
    defaultTiming: "Slow IV push",
    defaultDuration: "Stat",
    defaultInstruction: "Immediate management of symptomatic severe hypoglycemia; re-check RBS 15 mins post push",
  },
  {
    id: "ivf-mannitol-100",
    name: "Mannitol 20% Infusion 100ml",
    genericName: "MANNITOL 20% W/V",
    brandNames: ["Mannitol 20%", "Osmitrol Infusion"],
    category: "IV Fluids & Electrolytes",
    form: "IV Fluid",
    defaultStrength: "100ml (20%)",
    defaultDosage: "100ml IV over 20-30 min",
    defaultTiming: "Rapid IV infusion",
    defaultDuration: "Stat / Q8H SOS",
    defaultInstruction: "Osmotic diuretic for reducing elevated intracranial pressure or intraocular pressure; ensure adequate catheterization",
  },
  {
    id: "ivf-isolyte-p",
    name: "Isolyte P Paediatric Maintenance Fluid 500ml",
    genericName: "BALANCED MULTIPLE ELECTROLYTES WITH 5% DEXTROSE",
    brandNames: ["Isolyte P", "Pediatric Electrolyte Solution"],
    category: "IV Fluids & Electrolytes",
    form: "IV Fluid",
    defaultStrength: "500ml",
    defaultDosage: "Calculated per body weight",
    defaultTiming: "Slow IV microdrip",
    defaultDuration: "24 hours",
    defaultInstruction: "Pediatric maintenance fluid; monitor serum electrolytes and precise urine output",
  },

  // =========================================================================
  // INJECTABLES & EMERGENCY DRUGS
  // =========================================================================
  {
    id: "inj-ceftriaxone-1g",
    name: "Inj. Ceftriaxone 1g",
    genericName: "CEFTRIAXONE SODIUM",
    brandNames: ["Monocef 1g", "Oframax 1g", "Ceftriaxone 1g Vial"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "1000mg",
    defaultDosage: "1g IV BD",
    defaultTiming: "Slow IV / In 100ml NS",
    defaultDuration: "3-5 days",
    defaultInstruction: "Dilute in sterile water/100ml NS and infuse over 15-20 minutes; test dose / AST mandatory",
  },
  {
    id: "inj-pantoprazole-40",
    name: "Inj. Pantoprazole 40mg",
    genericName: "PANTOPRAZOLE SODIUM",
    brandNames: ["Pan 40 IV", "Pantocid IV", "Pantop IV"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "40mg",
    defaultDosage: "40mg IV OD",
    defaultTiming: "Slow IV push / In 100ml NS",
    defaultDuration: "3 days",
    defaultInstruction: "Reconstitute with 10ml normal saline; give slow IV push before breakfast or stat for acute gastritis",
  },
  {
    id: "inj-ondansetron-4",
    name: "Inj. Ondansetron 4mg/2ml",
    genericName: "ONDANSETRON HYDROCHLORIDE",
    brandNames: ["Emeset 2ml", "Zofran Inj", "Ondem Inj"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "4mg/2ml",
    defaultDosage: "4mg slow IV / IM",
    defaultTiming: "Slow IV push",
    defaultDuration: "Stat / TDS SOS",
    defaultInstruction: "Slow IV over 2 minutes for acute vomiting / nausea",
  },
  {
    id: "inj-tramadol-50",
    name: "Inj. Tramadol 50mg/ml",
    genericName: "TRAMADOL HYDROCHLORIDE",
    brandNames: ["Tramazac 2ml", "Supridol Inj", "Contramal"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "100mg/2ml",
    defaultDosage: "50-100mg slow IV",
    defaultTiming: "Slow IV in 100ml NS / Deep IM",
    defaultDuration: "SOS",
    defaultInstruction: "Always give with antiemetic (Inj. Emeset) slowly over 10-15 mins to prevent severe nausea & vomiting",
  },
  {
    id: "inj-diclofenac-75",
    name: "Inj. Diclofenac Sodium 75mg/1ml",
    genericName: "DICLOFENAC SODIUM",
    brandNames: ["Dynapar AQ", "Voveran 1ml", "Jonac Inj"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "75mg/1ml",
    defaultDosage: "75mg deep IM stat",
    defaultTiming: "Deep intragluteal IM only",
    defaultDuration: "Stat / BD SOS",
    defaultInstruction: "Deep intragluteal injection in upper outer quadrant; do NOT give IV push",
  },
  {
    id: "inj-pcm-iv-1000",
    name: "Inj. Paracetamol 1000mg/100ml IV Infusion",
    genericName: "PARACETAMOL 1000MG IV INFUSION",
    brandNames: ["Paracip IV 100ml", "Dolo IV", "PCM 100ml Infusion"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "1000mg/100ml",
    defaultDosage: "1 bottle (100ml) IV over 15 min",
    defaultTiming: "IV infusion",
    defaultDuration: "Stat / TDS SOS",
    defaultInstruction: "Infuse over 15 minutes for acute hyperpyrexia or severe post-operative pain",
  },
  {
    id: "inj-hydrocortisone-100",
    name: "Inj. Hydrocortisone 100mg",
    genericName: "HYDROCORTISONE SODIUM SUCCINATE",
    brandNames: ["Primacort 100", "Efcorlin 100", "Hydrocort Vial"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "100mg",
    defaultDosage: "100mg IV stat",
    defaultTiming: "Slow IV push",
    defaultDuration: "Stat / Q8H",
    defaultInstruction: "For acute severe asthma, anaphylaxis, septic shock, and adrenal crisis",
  },
  {
    id: "inj-dexa-8",
    name: "Inj. Dexamethasone 8mg/2ml",
    genericName: "DEXAMETHASONE SODIUM PHOSPHATE",
    brandNames: ["Decdan 2ml", "Dexona 2ml"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "4mg/ml (2ml)",
    defaultDosage: "4-8mg IV / IM stat",
    defaultTiming: "Slow IV / IM",
    defaultDuration: "Stat / BD",
    defaultInstruction: "Potent anti-inflammatory corticosteroid for acute airway edema, severe allergies, and cerebral edema",
  },
  {
    id: "inj-avil-2",
    name: "Inj. Pheniramine Maleate (Avil) 2ml",
    genericName: "PHENIRAMINE MALEATE",
    brandNames: ["Avil Inj 2ml"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "22.75mg/ml (2ml)",
    defaultDosage: "1 ampoule (2ml) slow IV / IM",
    defaultTiming: "Slow IV push / IM",
    defaultDuration: "Stat / SOS",
    defaultInstruction: "Antihistamine for acute allergic reactions, urticaria, and drug reactions; causes mild sedation",
  },
  {
    id: "inj-deriphyllin-2",
    name: "Inj. Deriphyllin 2ml",
    genericName: "ETOPHYLLINE + THEOPHYLLINE",
    brandNames: ["Deriphyllin Inj 2ml"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "2ml",
    defaultDosage: "1 ampoule (2ml) slow IV / IM",
    defaultTiming: "Very slow IV push over 5 mins",
    defaultDuration: "Stat / BD SOS",
    defaultInstruction: "Bronchodilator for acute bronchial asthma and COPD exacerbation; inject very slowly to prevent tachycardia",
  },
  {
    id: "inj-lasix-20",
    name: "Inj. Furosemide (Lasix) 20mg/2ml",
    genericName: "FUROSEMIDE",
    brandNames: ["Lasix 2ml", "Salurin Inj"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "20mg/2ml",
    defaultDosage: "20-40mg slow IV stat",
    defaultTiming: "Slow IV push",
    defaultDuration: "Stat / BD SOS",
    defaultInstruction: "Loop diuretic for acute pulmonary edema, hypertensive emergency, and congestive heart failure; monitor BP and urine output",
  },
  {
    id: "inj-tranexa-500",
    name: "Inj. Tranexamic Acid 500mg/5ml",
    genericName: "TRANEXAMIC ACID",
    brandNames: ["Pause 500", "Texakind Inj", "Trapic 5ml"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "500mg/5ml",
    defaultDosage: "500mg slow IV",
    defaultTiming: "Slow IV over 5-10 mins",
    defaultDuration: "Stat / TDS",
    defaultInstruction: "Antifibrinolytic for acute hemorrhage, epistaxis, post-extraction bleeding, and menorrhagia; inject slowly",
  },
  {
    id: "inj-tt-05",
    name: "Inj. Tetanus Toxoid (TT) 0.5ml",
    genericName: "TETANUS TOXOID VACCINE",
    brandNames: ["TT 0.5ml", "Tetvac", "Tetanus Vaccine"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "0.5ml",
    defaultDosage: "0.5ml deep IM stat",
    defaultTiming: "Intramuscular (Deltoid)",
    defaultDuration: "Single dose stat",
    defaultInstruction: "Prophylaxis for cuts, road traffic accidents, lacerations, and contaminated animal bites",
  },
  {
    id: "inj-atropine-06",
    name: "Inj. Atropine Sulphate 0.6mg/ml",
    genericName: "ATROPINE SULPHATE",
    brandNames: ["Atropine Inj 1ml"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "0.6mg/ml",
    defaultDosage: "0.6mg IV stat",
    defaultTiming: "Rapid IV push",
    defaultDuration: "Stat / Repeat PRN",
    defaultInstruction: "Anticholinergic for severe symptomatic bradycardia and organophosphate poisoning antidote",
  },
  {
    id: "inj-adrenaline-1",
    name: "Inj. Adrenaline (Epinephrine) 1:1000",
    genericName: "ADRENALINE (EPINEPHRINE) 1:1000",
    brandNames: ["Adrenaline Inj 1ml", "EpiPen Ampoule"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "1mg/ml (1:1000)",
    defaultDosage: "0.5ml (0.5mg) IM stat",
    defaultTiming: "Anterolateral thigh IM",
    defaultDuration: "Stat / Repeat in 5-10m if needed",
    defaultInstruction: "CRITICAL FIRST-LINE for acute anaphylactic shock and severe angioedema; inject IM in mid-outer thigh",
  },
  {
    id: "inj-lignocaine-2-plain",
    name: "Inj. Lignocaine 2% Plain (30ml Vial)",
    genericName: "LIGNOCAINE HYDROCHLORIDE 2%",
    brandNames: ["Xylocaine 2% Plain", "Lox 2% 30ml"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "20mg/ml (2%)",
    defaultDosage: "Infiltration as required",
    defaultTiming: "Local subcutaneous infiltration",
    defaultDuration: "Procedure use",
    defaultInstruction: "Local anaesthetic for suturing, abscess drainage, excision biopsy; aspirate before injecting to avoid intravascular entry",
  },
  {
    id: "inj-drotaverine-40",
    name: "Inj. Drotaverine 40mg/2ml",
    genericName: "DROTAVERINE HYDROCHLORIDE",
    brandNames: ["Drotin Inj 2ml", "Dotraverine"],
    category: "Injectables & Emergency",
    form: "Injection",
    defaultStrength: "40mg/2ml",
    defaultDosage: "40mg IM / slow IV",
    defaultTiming: "Deep IM / slow IV",
    defaultDuration: "Stat / BD SOS",
    defaultInstruction: "Smooth muscle antispasmodic for acute ureteric colic, biliary colic, and acute intestinal spasms",
  },

  // =========================================================================
  // OINTMENTS, GELS & TOPICALS
  // =========================================================================
  {
    id: "oint-betadine-5",
    name: "Povidone Iodine 5% Ointment (Betadine 20g)",
    genericName: "POVIDONE IODINE 5% W/W",
    brandNames: ["Betadine Ointment 20g", "Cipladine 5%", "Wokadine 5%"],
    category: "Ointments, Gels & Topicals",
    form: "Ointment",
    defaultStrength: "5% w/w (20g)",
    defaultDosage: "Apply locally BD",
    defaultTiming: "After wound cleaning",
    defaultDuration: "5-7 days",
    defaultInstruction: "Broad-spectrum antiseptic microbicide for cuts, scrapes, minor burns, and post-operative dressing",
  },
  {
    id: "cream-silver-burnol",
    name: "Silver Sulfadiazine 1% Burn Cream (Burnol / Silverex)",
    genericName: "SILVER SULFADIAZINE 1% W/W",
    brandNames: ["Burnol Cream", "Silverex Ionic 20g", "Silvrpex Cream"],
    category: "Ointments, Gels & Topicals",
    form: "Cream",
    defaultStrength: "1% w/w (20g)",
    defaultDosage: "Apply thick sterile layer BD",
    defaultTiming: "Topical application",
    defaultDuration: "7-10 days",
    defaultInstruction: "Topical antimicrobial for first-degree and second-degree burns; cleanse burned area gently and apply thick sterile layer",
  },
  {
    id: "oint-mupirocin-2",
    name: "Mupirocin 2% Ointment (T-Bact / Bactroban)",
    genericName: "MUPIROCIN 2% W/W",
    brandNames: ["T-Bact 2% 5g", "Bactroban Ointment", "Mupirocin 5g"],
    category: "Ointments, Gels & Topicals",
    form: "Ointment",
    defaultStrength: "2% w/w (5g)",
    defaultDosage: "Apply locally TID",
    defaultTiming: "Clean and dry skin",
    defaultDuration: "5-7 days",
    defaultInstruction: "Potent topical antibiotic for impetigo, folliculitis, infected eczema, and primary superficial skin infections",
  },
  {
    id: "gel-diclofenac-volini",
    name: "Diclofenac Gel 1% (Volini / Omnigel 30g)",
    genericName: "DICLOFENAC DIETHYLAMINE + LINSEED OIL + METHYL SALICYLATE + MENTHOL",
    brandNames: ["Volini Gel 30g", "Omnigel 30g", "Voveran Emulgel"],
    category: "Ointments, Gels & Topicals",
    form: "Gel",
    defaultStrength: "1.16% w/w (30g)",
    defaultDosage: "Apply gently 3-4 times daily",
    defaultTiming: "Over painful joints/muscles",
    defaultDuration: "7 days",
    defaultInstruction: "Gently rub over sprains, strains, osteoarthritis, and neck/back pain; wash hands post application",
  },
  {
    id: "cream-fusidic-acid",
    name: "Fusidic Acid 2% Cream (Fucidin 10g)",
    genericName: "FUSIDIC ACID 2% W/W",
    brandNames: ["Fucidin Cream 10g", "Fuson Cream"],
    category: "Ointments, Gels & Topicals",
    form: "Cream",
    defaultStrength: "2% w/w (10g)",
    defaultDosage: "Apply locally BD",
    defaultTiming: "Topical application",
    defaultDuration: "5-7 days",
    defaultInstruction: "Antibacterial cream effective against staphylococcal skin lesions, paronychia, and superficial wound infections",
  },
  {
    id: "cream-soframycin",
    name: "Framycetin Sulphate 1% Skin Cream (Soframycin 30g)",
    genericName: "FRAMYCETIN SULPHATE 1% W/W",
    brandNames: ["Soframycin Cream 30g"],
    category: "Ointments, Gels & Topicals",
    form: "Cream",
    defaultStrength: "1% w/w (30g)",
    defaultDosage: "Apply locally BD",
    defaultTiming: "After cleaning",
    defaultDuration: "5 days",
    defaultInstruction: "Topical antibacterial cream for minor lacerations, ulcers, abrasions, and skin graft donor sites",
  },
  {
    id: "cream-clotrimazole",
    name: "Clotrimazole 1% Cream (Candid / Canesten 30g)",
    genericName: "CLOTRIMAZOLE 1% W/W",
    brandNames: ["Candid Cream 30g", "Canesten 1%", "Surfaz"],
    category: "Ointments, Gels & Topicals",
    form: "Cream",
    defaultStrength: "1% w/w (30g)",
    defaultDosage: "Apply thin film BD",
    defaultTiming: "Clean and dry skin",
    defaultDuration: "2-3 weeks",
    defaultInstruction: "Topical broad-spectrum antifungal for tinea cruris (jock itch), tinea corporis (ringworm), and fungal intertrigo",
  },
  {
    id: "gel-lignocaine-jelly",
    name: "Lignocaine 2% Anaesthetic Jelly (Lox 2% Jelly 30g)",
    genericName: "LIGNOCAINE HYDROCHLORIDE 2% JELLY",
    brandNames: ["Lox 2% Jelly 30g", "Xylocaine 2% Jelly"],
    category: "Ointments, Gels & Topicals",
    form: "Gel",
    defaultStrength: "2% w/w (30g)",
    defaultDosage: "Instill 5-10ml into urethra",
    defaultTiming: "5-10 min prior to catheterization",
    defaultDuration: "Single procedure",
    defaultInstruction: "Sterile lubricating and anaesthetic gel for catheter insertion, cystoscopy, and rectal examinations",
  },
  {
    id: "lotion-permethrin-5",
    name: "Permethrin 5% Anti-Scabies Lotion (Permite 60ml)",
    genericName: "PERMETHRIN 5% W/V",
    brandNames: ["Permite 5% 60ml", "Scaboma Lotion"],
    category: "Ointments, Gels & Topicals",
    form: "Lotion",
    defaultStrength: "5% w/v (60ml)",
    defaultDosage: "Apply neck-down overnight",
    defaultTiming: "Night before bed",
    defaultDuration: "Single application; repeat in 7d",
    defaultInstruction: "Apply thoroughly from neck to toe after bath; wash off after 8-12 hours; treat all household contacts simultaneously",
  },
  {
    id: "lotion-calamine",
    name: "Calamine + Aloe Vera Soothing Lotion (100ml)",
    genericName: "CALAMINE + ZINC OXIDE + ALOE VERA",
    brandNames: ["Lacto Calamine 100ml", "Caladryl Lotion"],
    category: "Ointments, Gels & Topicals",
    form: "Lotion",
    defaultStrength: "100ml",
    defaultDosage: "Apply locally 2-3 times daily",
    defaultTiming: "Topical application",
    defaultDuration: "5-7 days",
    defaultInstruction: "Shake well before use; soothing protective lotion for sunburn, prickly heat, urticaria, and chickenpox itching",
  },

  // =========================================================================
  // SURGICAL & MEDICAL CONSUMABLES
  // =========================================================================
  {
    id: "surg-ryles-tube-16",
    name: "Ryle's Tube / Nasogastric (NG) Tube 16Fr",
    genericName: "NASOGASTRIC ENTERAL FEEDING & DECOMPRESSION TUBE WITH RADIO-OPAQUE LINE",
    brandNames: ["Ryle's Tube 16Fr (Romsons)", "Ryle's Tube 14Fr", "NG Tube 18Fr"],
    category: "Surgical & Medical Consumables",
    form: "Tube",
    defaultStrength: "16Fr (105cm length)",
    defaultDosage: "1 tube for insertion",
    defaultTiming: "Under sterile lubricant",
    defaultDuration: "Indwelling (Max 14 days)",
    defaultInstruction: "Lubricate with Lignocaine jelly; confirm intragastric placement via epigastric auscultation and aspiration before feeding",
  },
  {
    id: "surg-iv-infusion-set",
    name: "IV Infusion Set with Air Vent & Needle (Vented)",
    genericName: "STERILE SINGLE-USE INTRAVENOUS INFUSION SET (20 DROPS/ML)",
    brandNames: ["Romsons IV Set", "B.Braun Intrafix", "Nipro IV Set"],
    category: "Surgical & Medical Consumables",
    form: "Medical Consumable",
    defaultStrength: "Standard 20 drops/ml",
    defaultDosage: "1 set per IV line",
    defaultTiming: "Connect with IV Cannula",
    defaultDuration: "Change after 72 hours",
    defaultInstruction: "Purge air completely from line before attaching to cannula; adjust drop rate via precision roller clamp",
  },
  {
    id: "surg-microdrip-set",
    name: "Paediatric Measured Volume Burette Set (100ml / 150ml)",
    genericName: "MEASURED VOLUME PEDIATRIC FLUID INFUSION SET (60 DROPS/ML)",
    brandNames: ["Romsons Burette Set 100ml", "Voluset 150ml"],
    category: "Surgical & Medical Consumables",
    form: "Medical Consumable",
    defaultStrength: "60 drops/ml (100ml chamber)",
    defaultDosage: "1 set for precision infusion",
    defaultTiming: "Pediatric / ICU IV line",
    defaultDuration: "Single patient use",
    defaultInstruction: "Calibrated cylindrical chamber for exact pediatric dose fluid delivery and drug dilution",
  },
  {
    id: "surg-bt-set",
    name: "Blood Transfusion (BT) Set with 200µm Mesh Filter",
    genericName: "STERILE BLOOD ADMINISTRATION SET WITH 200 MICRON FILTER",
    brandNames: ["Romsons BT Set", "Transflow BT Set"],
    category: "Surgical & Medical Consumables",
    form: "Medical Consumable",
    defaultStrength: "200 micron mesh filter",
    defaultDosage: "1 set per blood unit",
    defaultTiming: "Blood / PRBC transfusion",
    defaultDuration: "Single blood bag use (Max 4 hours)",
    defaultInstruction: "Prime with 0.9% Normal Saline only; NEVER prime with Dextrose, Ringer Lactate, or distilled water",
  },
  {
    id: "surg-foley-catheter-16",
    name: "Foley's Balloon Catheter 2-Way (16Fr)",
    genericName: "STERILE SILICONIZED ELASTOMER 2-WAY FOLEY CATHETER WITH 30ML BALLOON",
    brandNames: ["Romsons Foley 16Fr", "Bardex Foley 14Fr/16Fr", "Rusch Foley Catheter"],
    category: "Surgical & Medical Consumables",
    form: "Catheter",
    defaultStrength: "16Fr (30ml balloon)",
    defaultDosage: "1 catheter for insertion",
    defaultTiming: "Strict sterile technique",
    defaultDuration: "Change after 14-21 days",
    defaultInstruction: "Lubricate with 2% Lignocaine jelly; inflate balloon with 10-15ml sterile distilled water (do NOT use saline)",
  },
  {
    id: "surg-urobag-2000",
    name: "Urine Collection Drainage Bag (Urobag 2000ml)",
    genericName: "CLOSED URINARY DRAINAGE SYSTEM 2000ML WITH NON-RETURN VALVE",
    brandNames: ["Romsons Urobag 2000ml", "Urotop Closed Drainage"],
    category: "Surgical & Medical Consumables",
    form: "Medical Consumable",
    defaultStrength: "2000ml capacity",
    defaultDosage: "1 bag attached to catheter",
    defaultTiming: "Continuous closed drainage",
    defaultDuration: "Change per protocol",
    defaultInstruction: "Keep drainage bag suspended below the level of the bladder at all times; avoid floor contact",
  },
  {
    id: "surg-iv-cannula-20",
    name: "IV Cannula / Venflon 20G (Pink) with Port",
    genericName: "STERILE INTRAVENOUS CANNULA 20G WITH INJECTION PORT & WINGS",
    brandNames: ["Venflon 20G Pink", "Jelco 20G", "BD Introcan 20G", "Romsons Vasofix"],
    category: "Surgical & Medical Consumables",
    form: "Medical Consumable",
    defaultStrength: "20G (Pink) - 60 ml/min flow",
    defaultDosage: "1 cannula for venipuncture",
    defaultTiming: "Aseptic peripheral vein entry",
    defaultDuration: "Rotate site after 72 hours",
    defaultInstruction: "Check blood flashback in flash chamber; flush with normal saline and secure firmly with sterile dressing",
  },
  {
    id: "surg-iv-cannula-22",
    name: "IV Cannula / Venflon 22G (Blue)",
    genericName: "STERILE INTRAVENOUS CANNULA 22G WITH INJECTION PORT",
    brandNames: ["Venflon 22G Blue", "BD Insyte 22G", "Romsons 22G"],
    category: "Surgical & Medical Consumables",
    form: "Medical Consumable",
    defaultStrength: "22G (Blue) - 36 ml/min flow",
    defaultDosage: "1 cannula",
    defaultTiming: "Peripheral vein cannulation",
    defaultDuration: "Rotate site after 72 hours",
    defaultInstruction: "Ideal for elderly and pediatric patients with fragile peripheral veins",
  },
  {
    id: "surg-suction-catheter-12",
    name: "Suction Catheter with Thumb Control (12Fr)",
    genericName: "STERILE DISPOSABLE ENDOBRONCHIAL SUCTION CATHETER (12FR)",
    brandNames: ["Romsons Suction Catheter 12Fr", "Vakutip 12Fr"],
    category: "Surgical & Medical Consumables",
    form: "Catheter",
    defaultStrength: "12Fr (50cm length)",
    defaultDosage: "1 unit for aspiration",
    defaultTiming: "As required under suction",
    defaultDuration: "Single use",
    defaultInstruction: "Insert without suction; apply thumb vacuum control while withdrawing with gentle rotating motion (<15 seconds)",
  },
  {
    id: "surg-et-tube-75",
    name: "Endotracheal (ET) Tube Cuffed 7.5mm",
    genericName: "STERILE CUFFED ENDOTRACHEAL TUBE WITH MURPHY EYE (7.5MM ID)",
    brandNames: ["Portex Cuffed ET Tube 7.5", "Romsons Aerotube 7.5"],
    category: "Surgical & Medical Consumables",
    form: "Tube",
    defaultStrength: "7.5mm ID Cuffed",
    defaultDosage: "1 tube for airway management",
    defaultTiming: "Direct laryngoscopy",
    defaultDuration: "Short-term airway",
    defaultInstruction: "Inflate cuff to 20-25 cm H2O; verify bilateral equal chest expansion and 5-point auscultation",
  },
  {
    id: "surg-oxygen-mask-prongs",
    name: "Nasal Oxygen Cannula (Twin-Bore Prongs) / Face Mask",
    genericName: "MEDICAL GRADE SOFT TWIN-BORE NASAL OXYGEN CANNULA (2 METERS)",
    brandNames: ["Oxy-Flow Nasal Prongs", "Standard Oxygen Mask Adult"],
    category: "Surgical & Medical Consumables",
    form: "Medical Consumable",
    defaultStrength: "Standard 2-meter tubing",
    defaultDosage: "1 set for O2 therapy",
    defaultTiming: "Continuous / SOS",
    defaultDuration: "Single patient use",
    defaultInstruction: "Set flow rate: 1-4 L/min for nasal cannula (delivers 24-36% FiO2); 5-8 L/min for simple oxygen mask",
  },
  {
    id: "surg-syringe-5ml",
    name: "Disposable Sterile Syringe 5ml with 23G Needle",
    genericName: "STERILE THREE-PIECE DISPOSABLE SYRINGE WITH HYPODERMIC NEEDLE",
    brandNames: ["Dispovan 5ml", "BD Emerald 5ml", "HMD Dispo Van"],
    category: "Surgical & Medical Consumables",
    form: "Medical Consumable",
    defaultStrength: "5ml with 23G 1-inch needle",
    defaultDosage: "1 syringe per injection",
    defaultTiming: "Single use",
    defaultDuration: "Single use only",
    defaultInstruction: "Non-pyrogenic, sterile blister packed; discard immediately into puncture-proof sharps container",
  },
  {
    id: "surg-gauze-cotton",
    name: "Sterile Gauze Swabs (10x10cm) & Absorbent Cotton Roll",
    genericName: "100% PURIFIED MEDICAL ABSORBENT COTTON & STERILE GAUZE PADS",
    brandNames: ["Sterile Gauze Swab 10x10", "Absorbent Cotton Roll 500g", "Gamjee Pad"],
    category: "Surgical & Medical Consumables",
    form: "Medical Consumable",
    defaultStrength: "10cm x 10cm (12-ply)",
    defaultDosage: "As required for wound dressing",
    defaultTiming: "Aseptic dressing change",
    defaultDuration: "Daily / alternate days",
    defaultInstruction: "Autoclaved packaging; use with Povidone Iodine / Normal Saline for surgical and trauma wound cleansing",
  },
  {
    id: "surg-micropore-1inch",
    name: "Micropore Surgical Paper Adhesive Tape (1 Inch / 2 Inch)",
    genericName: "HYPOALLERGENIC NON-WOVEN SURGICAL PAPER TAPE",
    brandNames: ["3M Micropore 1 inch", "3M Micropore 2 inch", "Dynapore Tape"],
    category: "Surgical & Medical Consumables",
    form: "Medical Consumable",
    defaultStrength: "1 inch x 9.1 m / 2 inch x 9.1 m",
    defaultDosage: "1 roll for securement",
    defaultTiming: "Dressing / Cannula securement",
    defaultDuration: "As needed",
    defaultInstruction: "Breathable, hypoallergenic surgical paper tape gentle on sensitive skin and fragile tissue",
  },
  {
    id: "surg-crepe-bandage-10",
    name: "Crepe Elastic Support Bandage (10cm / 15cm)",
    genericName: "COTTON ELASTIC EXTENSIBLE CREPE BANDAGE FOR SPRAINS",
    brandNames: ["Flamingo Crepe Bandage 10cm", "Hansaplast Crepe 15cm", "Dynacrepe"],
    category: "Surgical & Medical Consumables",
    form: "Medical Consumable",
    defaultStrength: "10 cm x 4 m / 15 cm x 4 m",
    defaultDosage: "1 bandage",
    defaultTiming: "Joint compression / sprain support",
    defaultDuration: "Daytime wear",
    defaultInstruction: "Wrap firmly in figure-of-eight; check distal pulses and nail bed capillary refill to prevent constriction",
  },
  {
    id: "surg-gloves-7",
    name: "Sterile Surgical Latex Gloves (Size 7.0 / 7.5 Pair)",
    genericName: "PRE-POWDERED / POWDER-FREE ANATOMICAL SURGICAL LATEX GLOVES",
    brandNames: ["Ansell Gammex Size 7.0", "Surgicare Latex Gloves", "Kanam Surgical"],
    category: "Surgical & Medical Consumables",
    form: "Medical Consumable",
    defaultStrength: "Size 7.0 / 7.5",
    defaultDosage: "1 pair per procedure",
    defaultTiming: "Aseptic clinical procedures",
    defaultDuration: "Single procedure use",
    defaultInstruction: "Peel open pouch aseptically; do not touch outer sterile glove surface with unwashed hands",
  },
  {
    id: "surg-suture-vicryl-ethilon",
    name: "Surgical Suture (Vicryl 3-0 / Ethilon 3-0 / Silk 2-0)",
    genericName: "STERILE SYNTHETIC ABSORBABLE / NON-ABSORBABLE SUTURE WITH CUTTING NEEDLE",
    brandNames: ["Ethicon Vicryl 3-0", "Ethicon Ethilon 3-0", "Mersilk 2-0"],
    category: "Surgical & Medical Consumables",
    form: "Medical Consumable",
    defaultStrength: "3-0 (19mm 3/8c Reverse Cutting)",
    defaultDosage: "1-2 foils for wound closure",
    defaultTiming: "Wound repair",
    defaultDuration: "Remove non-absorbable after 5-10 days",
    defaultInstruction: "Vicryl (absorbable) for deep subcutaneous tissues; Ethilon (nylon monofilament) for clean cosmetic skin closure",
  },
];

export function searchDrugs(query: string, categoryFilter: string = "All"): DrugItem[] {
  const q = query.trim().toLowerCase();
  return DRUG_LIBRARY.filter((item) => {
    const matchesCategory =
      categoryFilter === "All" || item.category.toLowerCase() === categoryFilter.toLowerCase();
    if (!matchesCategory) return false;

    if (!q) return true;

    const matchesName = item.name.toLowerCase().includes(q);
    const matchesGeneric = item.genericName.toLowerCase().includes(q);
    const matchesBrands = item.brandNames.some((b) => b.toLowerCase().includes(q));
    const matchesCat = item.category.toLowerCase().includes(q);

    return matchesName || matchesGeneric || matchesBrands || matchesCat;
  });
}
