export interface DrugItem {
  id: string;
  name: string;
  genericName: string;
  brandNames: string[];
  category: string;
  form: 'Tablet' | 'Capsule' | 'Syrup' | 'Injection' | 'Ointment' | 'Drops' | 'Inhaler' | 'Sachet';
  defaultStrength: string;
  defaultDosage: string;
  defaultTiming: string;
  defaultDuration: string;
  defaultInstruction: string;
}

export const DRUG_CATEGORIES = [
  "All",
  "Pain & Fever",
  "Antibiotics",
  "Gastro & Antacids",
  "Cough, Cold & Allergy",
  "Cardio & BP",
  "Diabetes",
  "Vitamins & Supplements",
  "Dermatology",
  "Eye & ENT",
] as const;

export const MEDICATION_PREFIXES = [
  "Tab.",
  "Cap.",
  "Syr.",
  "Inj.",
  "Oint.",
  "Drops",
  "Inh.",
  "Sachet",
  "Susp.",
  "Gel",
  "Cream",
] as const;

export const FORM_PREFIX_MAP: Record<DrugItem['form'], string> = {
  Tablet: "Tab.",
  Capsule: "Cap.",
  Syrup: "Syr.",
  Injection: "Inj.",
  Ointment: "Oint.",
  Drops: "Drops",
  Inhaler: "Inh.",
  Sachet: "Sachet",
};

export const DRUG_LIBRARY: DrugItem[] = [
  // --- PAIN & FEVER / NSAIDs ---
  {
    id: "pcm-650",
    name: "Paracetamol 650mg",
    genericName: "PARACETAMOL",
    brandNames: ["Dolo 650", "Calpol 650", "Pacimol 650"],
    category: "Pain & Fever",
    form: "Tablet",
    defaultStrength: "650mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "3 days",
    defaultInstruction: "Take with water after food; SOS for fever > 100°F or severe body ache",
  },
  {
    id: "pcm-500",
    name: "Paracetamol 500mg",
    genericName: "PARACETAMOL",
    brandNames: ["Crocin 500", "Calpol 500"],
    category: "Pain & Fever",
    form: "Tablet",
    defaultStrength: "500mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "3 days",
    defaultInstruction: "Take after food as needed for mild fever or headache",
  },
  {
    id: "aceclo-pcm",
    name: "Aceclofenac + Paracetamol",
    genericName: "ACECLOFENAC (100MG) + PARACETAMOL (325MG)",
    brandNames: ["Zerodol-P", "Hifenac-P", "Aroff Plus"],
    category: "Pain & Fever",
    form: "Tablet",
    defaultStrength: "100mg/325mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "5 days",
    defaultInstruction: "Take after food with plenty of water. Avoid on empty stomach.",
  },
  {
    id: "ibup-400",
    name: "Ibuprofen 400mg",
    genericName: "IBUPROFEN",
    brandNames: ["Brufen 400", "Ibugesic 400"],
    category: "Pain & Fever",
    form: "Tablet",
    defaultStrength: "400mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "3 days",
    defaultInstruction: "Anti-inflammatory pain relief; always take after meals",
  },
  {
    id: "diclo-50",
    name: "Diclofenac Sodium 50mg",
    genericName: "DICLOFENAC SODIUM",
    brandNames: ["Voveran 50", "Dicloran 50"],
    category: "Pain & Fever",
    form: "Tablet",
    defaultStrength: "50mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "3 days",
    defaultInstruction: "Take after food with an antacid if acidity-prone",
  },
  {
    id: "tram-pcm",
    name: "Tramadol + Paracetamol",
    genericName: "TRAMADOL (37.5MG) + PARACETAMOL (325MG)",
    brandNames: ["Ultracet", "Calpol-T"],
    category: "Pain & Fever",
    form: "Tablet",
    defaultStrength: "37.5mg/325mg",
    defaultDosage: "SOS",
    defaultTiming: "After food",
    defaultDuration: "3 days",
    defaultInstruction: "Take only SOS for severe acute pain; may cause mild drowsiness",
  },
  {
    id: "meftal-spas",
    name: "Mefenamic Acid + Dicyclomine",
    genericName: "MEFENAMIC ACID (250MG) + DICYCLOMINE (10MG)",
    brandNames: ["Meftal-Spas", "Spasmo-Proxyvon"],
    category: "Pain & Fever",
    form: "Tablet",
    defaultStrength: "250mg/10mg",
    defaultDosage: "SOS",
    defaultTiming: "After food",
    defaultDuration: "3 days",
    defaultInstruction: "For abdominal spasmodic cramps or dysmenorrhea",
  },

  // --- ANTIBIOTICS & ANTIMICROBIALS ---
  {
    id: "amox-clav-625",
    name: "Amoxicillin + Clavulanic Acid 625mg",
    genericName: "AMOXICILLIN (500MG) + CLAVULANIC ACID (125MG)",
    brandNames: ["Augmentin 625 Duo", "Clavam 625", "Moxikind-CV 625"],
    category: "Antibiotics",
    form: "Tablet",
    defaultStrength: "625mg",
    defaultDosage: "1-0-1",
    defaultTiming: "With food",
    defaultDuration: "5 days",
    defaultInstruction: "Complete the full 5-day course. Take at start of meals to minimize stomach upset.",
  },
  {
    id: "azithro-500",
    name: "Azithromycin 500mg",
    genericName: "AZITHROMYCIN",
    brandNames: ["Azee 500", "Zithrox 500", "Azithral 500"],
    category: "Antibiotics",
    form: "Tablet",
    defaultStrength: "500mg",
    defaultDosage: "1-0-0",
    defaultTiming: "Before food",
    defaultDuration: "3 days",
    defaultInstruction: "Single daily dose 1 hour before breakfast or 2 hours after meals",
  },
  {
    id: "cefix-200",
    name: "Cefixime 200mg",
    genericName: "CEFIXIME",
    brandNames: ["Zifi 200", "Taxim-O 200", "Cephalkem 200"],
    category: "Antibiotics",
    form: "Tablet",
    defaultStrength: "200mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "5 days",
    defaultInstruction: "Complete prescribed course for bacterial infection",
  },
  {
    id: "cipro-500",
    name: "Ciprofloxacin 500mg",
    genericName: "CIPROFLOXACIN",
    brandNames: ["Ciplox 500", "Cifran 500"],
    category: "Antibiotics",
    form: "Tablet",
    defaultStrength: "500mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "5 days",
    defaultInstruction: "Drink plenty of water during treatment. Avoid taking with antacids or dairy.",
  },
  {
    id: "oflox-ornid",
    name: "Ofloxacin + Ornidazole",
    genericName: "OFLOXACIN (200MG) + ORNIDAZOLE (500MG)",
    brandNames: ["O2", "Zenflox-OZ", "Oflomac-OZ"],
    category: "Antibiotics",
    form: "Tablet",
    defaultStrength: "200mg/500mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "5 days",
    defaultInstruction: "For mixed gastrointestinal or urinary infections; avoid alcohol completely",
  },
  {
    id: "doxy-100",
    name: "Doxycycline 100mg",
    genericName: "DOXYCYCLINE",
    brandNames: ["Doxicip 100", "Microdox-LBX"],
    category: "Antibiotics",
    form: "Capsule",
    defaultStrength: "100mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "7 days",
    defaultInstruction: "Take with a full glass of water sitting upright. Do not lie down for 30 minutes.",
  },
  {
    id: "nitro-100",
    name: "Nitrofurantoin 100mg SR",
    genericName: "NITROFURANTOIN SUSTAINED RELEASE",
    brandNames: ["Niftran 100", "Martifur MR 100"],
    category: "Antibiotics",
    form: "Tablet",
    defaultStrength: "100mg",
    defaultDosage: "1-0-1",
    defaultTiming: "With food",
    defaultDuration: "7 days",
    defaultInstruction: "For urinary tract infection; take with food or milk to enhance absorption",
  },
  {
    id: "metronid-400",
    name: "Metronidazole 400mg",
    genericName: "METRONIDAZOLE",
    brandNames: ["Flagyl 400", "Metrogyl 400"],
    category: "Antibiotics",
    form: "Tablet",
    defaultStrength: "400mg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "5 days",
    defaultInstruction: "For amoebic / anaerobic infections; strictly avoid alcohol",
  },

  // --- GASTROINTESTINAL & ANTACIDS ---
  {
    id: "panto-40",
    name: "Pantoprazole 40mg",
    genericName: "PANTOPRAZOLE",
    brandNames: ["Pan 40", "Pantocid 40", "Pantodac 40"],
    category: "Gastro & Antacids",
    form: "Tablet",
    defaultStrength: "40mg",
    defaultDosage: "1-0-0",
    defaultTiming: "Empty stomach",
    defaultDuration: "14 days",
    defaultInstruction: "Take 30 minutes before breakfast on empty stomach with water",
  },
  {
    id: "panto-dom-dsr",
    name: "Pantoprazole + Domperidone SR",
    genericName: "PANTOPRAZOLE (40MG) + DOMPERIDONE (30MG SR)",
    brandNames: ["Pan-D", "Pantocid-DSR", "Dompan-SR"],
    category: "Gastro & Antacids",
    form: "Capsule",
    defaultStrength: "40mg/30mg",
    defaultDosage: "1-0-0",
    defaultTiming: "Empty stomach",
    defaultDuration: "14 days",
    defaultInstruction: "Take 30-45 minutes before morning breakfast for GERD & reflux",
  },
  {
    id: "rabe-dom-dsr",
    name: "Rabeprazole + Domperidone",
    genericName: "RABEPRAZOLE (20MG) + DOMPERIDONE (30MG SR)",
    brandNames: ["Razo-D", "Cyra-D", "Rablet-D"],
    category: "Gastro & Antacids",
    form: "Capsule",
    defaultStrength: "20mg/30mg",
    defaultDosage: "1-0-0",
    defaultTiming: "Empty stomach",
    defaultDuration: "14 days",
    defaultInstruction: "Take before breakfast on empty stomach",
  },
  {
    id: "omez-20",
    name: "Omeprazole 20mg",
    genericName: "OMEPRAZOLE",
    brandNames: ["Omez 20", "Ocid 20"],
    category: "Gastro & Antacids",
    form: "Capsule",
    defaultStrength: "20mg",
    defaultDosage: "1-0-0",
    defaultTiming: "Empty stomach",
    defaultDuration: "14 days",
    defaultInstruction: "Take before breakfast for acid peptic relief",
  },
  {
    id: "ondan-4",
    name: "Ondansetron 4mg MD",
    genericName: "ONDANSETRON MOUTH DISSOLVING",
    brandNames: ["Emeset 4 MD", "Zofer 4 MD", "Vomikind MD"],
    category: "Gastro & Antacids",
    form: "Tablet",
    defaultStrength: "4mg",
    defaultDosage: "SOS",
    defaultTiming: "Before food",
    defaultDuration: "3 days",
    defaultInstruction: "Dissolve on tongue 30 mins before food or SOS for nausea/vomiting",
  },
  {
    id: "sucralfate-syr",
    name: "Sucralfate + Oxetacaine Suspension",
    genericName: "SUCRALFATE (1000MG) + OXETACAINE (20MG)",
    brandNames: ["Sucrafil-O", "Pegafate-O"],
    category: "Gastro & Antacids",
    form: "Syrup",
    defaultStrength: "10ml",
    defaultDosage: "1-0-1",
    defaultTiming: "Before food",
    defaultDuration: "14 days",
    defaultInstruction: "Take 10ml 1 hour before meals and at bedtime for mucosal healing",
  },
  {
    id: "ors-powder",
    name: "Oral Rehydration Salts (ORS)",
    genericName: "WHO FORMULA ORAL ELECTROLYTES",
    brandNames: ["Electral Powder", "Walyte ORS"],
    category: "Gastro & Antacids",
    form: "Sachet",
    defaultStrength: "21.8g Sachet",
    defaultDosage: "SOS",
    defaultTiming: "With food",
    defaultDuration: "3 days",
    defaultInstruction: "Dissolve 1 sachet entirely in 1 Litre of clean drinking water; sip frequently",
  },

  // --- COUGH, COLD & RESPIRATORY ---
  {
    id: "levocet-5",
    name: "Levocetirizine 5mg",
    genericName: "LEVOCETIRIZINE DIHYDROCHLORIDE",
    brandNames: ["Levocet 5", "1-AL 5", "Vozet 5"],
    category: "Cough, Cold & Allergy",
    form: "Tablet",
    defaultStrength: "5mg",
    defaultDosage: "0-0-1",
    defaultTiming: "At bedtime",
    defaultDuration: "5 days",
    defaultInstruction: "Take once daily at bedtime for allergic rhinitis, sneezing, and itching",
  },
  {
    id: "montair-lc",
    name: "Montelukast + Levocetirizine",
    genericName: "MONTELUKAST (10MG) + LEVOCETIRIZINE (5MG)",
    brandNames: ["Montair-LC", "Monticope", "Telekast-L"],
    category: "Cough, Cold & Allergy",
    form: "Tablet",
    defaultStrength: "10mg/5mg",
    defaultDosage: "0-0-1",
    defaultTiming: "At bedtime",
    defaultDuration: "10 days",
    defaultInstruction: "Take at bedtime for allergic asthma, chronic cough, and allergic rhinitis",
  },
  {
    id: "fexo-120",
    name: "Fexofenadine 120mg",
    genericName: "FEXOFENADINE HYDROCHLORIDE",
    brandNames: ["Allegra 120", "Fexova 120"],
    category: "Cough, Cold & Allergy",
    form: "Tablet",
    defaultStrength: "120mg",
    defaultDosage: "1-0-0",
    defaultTiming: "After food",
    defaultDuration: "7 days",
    defaultInstruction: "Non-sedating antihistamine for urticaria and seasonal allergies",
  },
  {
    id: "cough-dry",
    name: "Dextromethorphan + CPM Syrup",
    genericName: "DEXTROMETHORPHAN HBR + CHLORPHENIRAMINE MALEATE",
    brandNames: ["Ascoril-D", "Benadryl DR", "Alex Syrup"],
    category: "Cough, Cold & Allergy",
    form: "Syrup",
    defaultStrength: "10ml",
    defaultDosage: "1-1-1",
    defaultTiming: "After food",
    defaultDuration: "5 days",
    defaultInstruction: "10ml thrice daily for dry irritant cough; avoid driving if drowsy",
  },
  {
    id: "cough-wet",
    name: "Ambroxol + Levosalbutamol + Guaiphenesin",
    genericName: "MUCOLYTIC & BRONCHODILATOR EXPECTORANT",
    brandNames: ["Ascoril-LS", "Bro-Zedex LS", "Grilinctus-LS"],
    category: "Cough, Cold & Allergy",
    form: "Syrup",
    defaultStrength: "10ml",
    defaultDosage: "1-1-1",
    defaultTiming: "After food",
    defaultDuration: "5 days",
    defaultInstruction: "10ml thrice daily with lukewarm water to loosen chest congestion",
  },
  {
    id: "sinarest",
    name: "Paracetamol + Phenylephrine + Chlorpheniramine",
    genericName: "ANTIPYRETIC + DECONGESTANT + ANTIHISTAMINIC",
    brandNames: ["Sinarest", "Cheston Cold", "Wikoryl"],
    category: "Cough, Cold & Allergy",
    form: "Tablet",
    defaultStrength: "Combination",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "3 days",
    defaultInstruction: "Relief of common cold, blocked nose, fever, and headache",
  },
  {
    id: "asthalin-inhaler",
    name: "Salbutamol Inhaler 100mcg",
    genericName: "SALBUTAMOL SULFATE",
    brandNames: ["Asthalin Inhaler", "Ventorlin"],
    category: "Cough, Cold & Allergy",
    form: "Inhaler",
    defaultStrength: "100mcg/puff",
    defaultDosage: "SOS",
    defaultTiming: "As needed (SOS)",
    defaultDuration: "1 month",
    defaultInstruction: "1 to 2 puffs SOS for acute breathlessness or wheezing; rinse mouth after use",
  },
  {
    id: "foracort-200",
    name: "Budesonide + Formoterol Inhaler 200",
    genericName: "BUDESONIDE (200MCG) + FORMOTEROL (6MCG)",
    brandNames: ["Foracort 200 Rotacaps/Inhaler", "Budamate 200"],
    category: "Cough, Cold & Allergy",
    form: "Inhaler",
    defaultStrength: "200mcg/6mcg",
    defaultDosage: "1-0-1",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "1 inhalation twice daily regularly. Gargle and rinse mouth thoroughly with water after use.",
  },

  // --- CARDIOVASCULAR & ANTIHYPERTENSIVES ---
  {
    id: "telma-40",
    name: "Telmisartan 40mg",
    genericName: "TELMISARTAN",
    brandNames: ["Telma 40", "Telmikind 40", "Creser 40"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "40mg",
    defaultDosage: "1-0-0",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "Take in the morning regularly; monitor blood pressure regularly",
  },
  {
    id: "telma-am",
    name: "Telmisartan 40mg + Amlodipine 5mg",
    genericName: "TELMISARTAN (40MG) + AMLODIPINE (5MG)",
    brandNames: ["Telma-AM", "Telmikind-AM", "Amlokind-T"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "40mg/5mg",
    defaultDosage: "1-0-0",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "Take once daily in morning for essential hypertension",
  },
  {
    id: "amlong-5",
    name: "Amlodipine 5mg",
    genericName: "AMLODIPINE BESYLATE",
    brandNames: ["Amlong 5", "Stamlo 5", "Amlopin 5"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "5mg",
    defaultDosage: "0-0-1",
    defaultTiming: "At bedtime",
    defaultDuration: "1 month",
    defaultInstruction: "Take once daily at evening/bedtime; report pedal swelling if observed",
  },
  {
    id: "atorva-10",
    name: "Atorvastatin 10mg",
    genericName: "ATORVASTATIN CALCIUM",
    brandNames: ["Atorva 10", "Storvas 10", "Lipicure 10"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "10mg",
    defaultDosage: "0-0-1",
    defaultTiming: "At bedtime",
    defaultDuration: "1 month",
    defaultInstruction: "Lipid-lowering statin; take once daily at bedtime",
  },
  {
    id: "atorva-20",
    name: "Atorvastatin 20mg",
    genericName: "ATORVASTATIN CALCIUM",
    brandNames: ["Atorva 20", "Storvas 20", "Lipicure 20"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "20mg",
    defaultDosage: "0-0-1",
    defaultTiming: "At bedtime",
    defaultDuration: "1 month",
    defaultInstruction: "Take once daily at bedtime for dyslipidemia / cardiovascular risk reduction",
  },
  {
    id: "rosuvas-10",
    name: "Rosuvastatin 10mg",
    genericName: "ROSUVASTATIN CALCIUM",
    brandNames: ["Rosuvas 10", "Rozavel 10", "Roseday 10"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "10mg",
    defaultDosage: "0-0-1",
    defaultTiming: "At bedtime",
    defaultDuration: "1 month",
    defaultInstruction: "High-efficacy statin for cholesterol control; take at night",
  },
  {
    id: "metolar-25",
    name: "Metoprolol Succinate 25mg ER",
    genericName: "METOPROLOL SUCCINATE EXTENDED RELEASE",
    brandNames: ["Betaloc 25", "Metolar XR 25", "Pro lomet 25"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "25mg",
    defaultDosage: "1-0-0",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "Beta-blocker; take once daily with breakfast",
  },
  {
    id: "ecosprin-75",
    name: "Aspirin (Ecosprin) 75mg",
    genericName: "ASPIRIN (ENTERIC COATED)",
    brandNames: ["Ecosprin 75", "Delisprin 75"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "75mg",
    defaultDosage: "0-1-0",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "Antiplatelet cardioprotective dose; always take after afternoon or morning meal",
  },
  {
    id: "clopi-75",
    name: "Clopidogrel 75mg",
    genericName: "CLOPIDOGREL BISULFATE",
    brandNames: ["Clopilet 75", "Deplatt 75"],
    category: "Cardio & BP",
    form: "Tablet",
    defaultStrength: "75mg",
    defaultDosage: "0-1-0",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "Antiplatelet therapy; take daily after lunch",
  },

  // --- ANTIDIABETICS & ENDOCRINE ---
  {
    id: "metform-500",
    name: "Metformin 500mg SR",
    genericName: "METFORMIN HYDROCHLORIDE SUSTAINED RELEASE",
    brandNames: ["Glycomet 500 SR", "Cetapin 500", "Obimet 500"],
    category: "Diabetes",
    form: "Tablet",
    defaultStrength: "500mg",
    defaultDosage: "1-0-1",
    defaultTiming: "With food",
    defaultDuration: "1 month",
    defaultInstruction: "Take immediately with or after meals to prevent gastric irritation",
  },
  {
    id: "metform-1000",
    name: "Metformin 1000mg SR",
    genericName: "METFORMIN HYDROCHLORIDE SUSTAINED RELEASE",
    brandNames: ["Glycomet 1000 SR", "Gluconorm-SR 1g"],
    category: "Diabetes",
    form: "Tablet",
    defaultStrength: "1000mg",
    defaultDosage: "1-0-1",
    defaultTiming: "With food",
    defaultDuration: "1 month",
    defaultInstruction: "Take with meals; monitor HbA1c and renal parameters periodically",
  },
  {
    id: "glycomet-gp1",
    name: "Metformin 500mg + Glimepiride 1mg",
    genericName: "GLIMEPIRIDE (1MG) + METFORMIN (500MG SR)",
    brandNames: ["Glycomet-GP 1", "Amaryl M 1", "Zoryl-M 1"],
    category: "Diabetes",
    form: "Tablet",
    defaultStrength: "500mg/1mg",
    defaultDosage: "1-0-0",
    defaultTiming: "Before food",
    defaultDuration: "1 month",
    defaultInstruction: "Take 15-20 minutes before breakfast; maintain regular meal timings to avoid hypoglycemia",
  },
  {
    id: "glycomet-gp2",
    name: "Metformin 500mg + Glimepiride 2mg",
    genericName: "GLIMEPIRIDE (2MG) + METFORMIN (500MG SR)",
    brandNames: ["Glycomet-GP 2", "Amaryl M 2", "Zoryl-M 2"],
    category: "Diabetes",
    form: "Tablet",
    defaultStrength: "500mg/2mg",
    defaultDosage: "1-0-0",
    defaultTiming: "Before food",
    defaultDuration: "1 month",
    defaultInstruction: "Take before breakfast; keep glucose/sugar handy for hypoglycemia prevention",
  },
  {
    id: "teneli-20",
    name: "Teneligliptin 20mg",
    genericName: "TENELIGLIPTIN HYDROBROMIDE",
    brandNames: ["Ziten 20", "Tendia 20", "Tenelimac 20"],
    category: "Diabetes",
    form: "Tablet",
    defaultStrength: "20mg",
    defaultDosage: "1-0-0",
    defaultTiming: "Before food",
    defaultDuration: "1 month",
    defaultInstruction: "DPP-4 inhibitor; take once daily before breakfast",
  },
  {
    id: "dapa-10",
    name: "Dapagliflozin 10mg",
    genericName: "DAPAGLIFLOZIN PROPANEDIOL",
    brandNames: ["Forxiga 10", "Oxra 10", "Dapavel 10"],
    category: "Diabetes",
    form: "Tablet",
    defaultStrength: "10mg",
    defaultDosage: "1-0-0",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "SGLT-2 inhibitor; drink adequate water throughout the day",
  },
  {
    id: "thyro-50",
    name: "Levothyroxine 50mcg",
    genericName: "LEVOTHYROXINE SODIUM",
    brandNames: ["Thyronorm 50mcg", "Eltroxin 50mcg"],
    category: "Diabetes",
    form: "Tablet",
    defaultStrength: "50mcg",
    defaultDosage: "1-0-0",
    defaultTiming: "Empty stomach",
    defaultDuration: "1 month",
    defaultInstruction: "Take early morning on empty stomach with plain water at least 45 mins before tea/coffee",
  },
  {
    id: "thyro-100",
    name: "Levothyroxine 100mcg",
    genericName: "LEVOTHYROXINE SODIUM",
    brandNames: ["Thyronorm 100mcg", "Eltroxin 100mcg"],
    category: "Diabetes",
    form: "Tablet",
    defaultStrength: "100mcg",
    defaultDosage: "1-0-0",
    defaultTiming: "Empty stomach",
    defaultDuration: "1 month",
    defaultInstruction: "Take early morning on empty stomach with plain water. Repeat TSH in 8-12 weeks.",
  },

  // --- VITAMINS, MINERALS & SUPPLEMENTS ---
  {
    id: "shelcal-500",
    name: "Calcium 500mg + Vitamin D3",
    genericName: "CALCIUM CARBONATE (500MG ELEMENTAL) + VITAMIN D3 (250 IU)",
    brandNames: ["Shelcal 500", "Cipcal 500", "Gemcal"],
    category: "Vitamins & Supplements",
    form: "Tablet",
    defaultStrength: "500mg",
    defaultDosage: "0-1-0",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "Take once daily after lunch with water",
  },
  {
    id: "vit-d3-60k",
    name: "Cholecalciferol (Vitamin D3) 60,000 IU",
    genericName: "CHOLECALCIFEROL VITAMIN D3",
    brandNames: ["Uprise-D3 60K", "Calcirol 60K Sachet", "D-Rise 60K"],
    category: "Vitamins & Supplements",
    form: "Capsule",
    defaultStrength: "60,000 IU",
    defaultDosage: "Weekly once",
    defaultTiming: "After food",
    defaultDuration: "2 months",
    defaultInstruction: "Take 1 capsule once weekly (e.g. every Sunday after breakfast with milk) for 8 weeks",
  },
  {
    id: "neurobion",
    name: "Vitamin B-Complex + B12",
    genericName: "THIAMINE, RIBOFLAVIN, NIACINAMIDE, PYRIDOXINE, CYANOCOBALAMIN",
    brandNames: ["Neurobion Forte", "Becosules", "Cobadex Forte"],
    category: "Vitamins & Supplements",
    form: "Tablet",
    defaultStrength: "High Potency B-Complex",
    defaultDosage: "1-0-0",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "Daily multivitamin after breakfast to maintain nerve health & energy",
  },
  {
    id: "iron-folic",
    name: "Ferrous Ascorbate + Folic Acid",
    genericName: "FERROUS ASCORBATE (100MG ELEMENTAL IRON) + FOLIC ACID (1.5MG)",
    brandNames: ["Orofer-XT", "HB-Rich", "Feronia-XT"],
    category: "Vitamins & Supplements",
    form: "Tablet",
    defaultStrength: "100mg/1.5mg",
    defaultDosage: "0-0-1",
    defaultTiming: "After food",
    defaultDuration: "1 month",
    defaultInstruction: "For iron deficiency anemia; take at bedtime. Avoid taking with tea, coffee, or milk.",
  },
  {
    id: "vit-c-zinc",
    name: "Vitamin C 500mg + Zinc",
    genericName: "ASCORBIC ACID (500MG) + ZINC (5MG)",
    brandNames: ["Limcee Chewable", "Celin 500", "Zinconia"],
    category: "Vitamins & Supplements",
    form: "Tablet",
    defaultStrength: "500mg",
    defaultDosage: "1-0-0",
    defaultTiming: "After food",
    defaultDuration: "15 days",
    defaultInstruction: "Chewable tablet; immune support for recovery from infections",
  },

  // --- DERMATOLOGY & TOPICALS ---
  {
    id: "tbact-oint",
    name: "Mupirocin 2% Ointment",
    genericName: "MUPIROCIN OINTMENT 2% W/W",
    brandNames: ["T-Bact Ointment", "Bactroban"],
    category: "Dermatology",
    form: "Ointment",
    defaultStrength: "2%",
    defaultDosage: "1-0-1",
    defaultTiming: "As needed (SOS)",
    defaultDuration: "7 days",
    defaultInstruction: "Apply thinly over cleaned affected area twice daily for bacterial skin infection",
  },
  {
    id: "candid-cream",
    name: "Clotrimazole 1% Cream",
    genericName: "CLOTRIMAZOLE CREAM 1% W/W",
    brandNames: ["Candid Cream", "Canesten"],
    category: "Dermatology",
    form: "Ointment",
    defaultStrength: "1%",
    defaultDosage: "1-0-1",
    defaultTiming: "As needed (SOS)",
    defaultDuration: "14 days",
    defaultInstruction: "Clean and dry skin thoroughly; apply twice daily for fungal ringworm / tinea infection",
  },
  {
    id: "betnovate-n",
    name: "Betamethasone + Neomycin Cream",
    genericName: "BETAMETHASONE VALERATE (0.1%) + NEOMYCIN (0.5%)",
    brandNames: ["Betnovate-N", "Cortiderm-N"],
    category: "Dermatology",
    form: "Ointment",
    defaultStrength: "0.1%/0.5%",
    defaultDosage: "1-0-1",
    defaultTiming: "As needed (SOS)",
    defaultDuration: "5 days",
    defaultInstruction: "Apply sparingly on affected eczema / dermatitis lesion for short-term relief",
  },

  // --- EYE & ENT DROPS ---
  {
    id: "moxi-eye",
    name: "Moxifloxacin 0.5% Eye Drops",
    genericName: "MOXIFLOXACIN OPHTHALMIC SOLUTION 0.5% W/V",
    brandNames: ["Moxicip Eye Drops", "Vigamox"],
    category: "Eye & ENT",
    form: "Drops",
    defaultStrength: "0.5%",
    defaultDosage: "1-1-1",
    defaultTiming: "As needed (SOS)",
    defaultDuration: "5 days",
    defaultInstruction: "Instill 1 drop in affected eye(s) 3 times daily for conjunctivitis",
  },
  {
    id: "refresh-tears",
    name: "Carboxymethylcellulose 0.5% Eye Drops",
    genericName: "CARBOXYMETHYLCELLULOSE LUBRICANT EYE DROPS",
    brandNames: ["Refresh Tears", "Tears Naturale", "Lubrex"],
    category: "Eye & ENT",
    form: "Drops",
    defaultStrength: "0.5%",
    defaultDosage: "1-1-1-1",
    defaultTiming: "As needed (SOS)",
    defaultDuration: "1 month",
    defaultInstruction: "Instill 1-2 drops 3 to 4 times daily for dry, tired, or strained eyes",
  },
  {
    id: "ciplox-ear",
    name: "Ciprofloxacin Ear Drops",
    genericName: "CIPROFLOXACIN 0.3% W/V EAR DROPS",
    brandNames: ["Ciplox Ear Drops", "Cifran Ear Drops"],
    category: "Eye & ENT",
    form: "Drops",
    defaultStrength: "0.3%",
    defaultDosage: "1-0-1",
    defaultTiming: "As needed (SOS)",
    defaultDuration: "5 days",
    defaultInstruction: "Instill 3-4 drops into affected ear canal twice daily; keep ear dry",
  },
  {
    id: "otrivin-drops",
    name: "Xylometazoline 0.1% Nasal Drops",
    genericName: "XYLOMETAZOLINE HYDROCHLORIDE 0.1%",
    brandNames: ["Otrivin Nasal Drops", "Nasivion"],
    category: "Eye & ENT",
    form: "Drops",
    defaultStrength: "0.1%",
    defaultDosage: "1-0-1",
    defaultTiming: "As needed (SOS)",
    defaultDuration: "3 days",
    defaultInstruction: "Instill 2 drops in each nostril for blocked nose; do NOT use for more than 5 consecutive days",
  },
];

export function searchDrugs(query: string, categoryFilter: string = "All"): DrugItem[] {
  const q = query.trim().toLowerCase();
  return DRUG_LIBRARY.filter((item) => {
    const matchesCategory =
      categoryFilter === "All" || item.category.toLowerCase() === categoryFilter.toLowerCase();
    if (!matchesCategory) return false;

    if (!q) return true;

    const matchesName = item.name.toLowerCase().includes(q);
    const matchesGeneric = item.genericName.toLowerCase().includes(q);
    const matchesBrands = item.brandNames.some((b) => b.toLowerCase().includes(q));
    const matchesCat = item.category.toLowerCase().includes(q);

    return matchesName || matchesGeneric || matchesBrands || matchesCat;
  });
}
